### ISSUE TITLE
Admin.jsp not working anymore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mondain/red5#41]
```
What steps will reproduce the problem?
1. I am using the current red5 1.0 r4195
2. I copied the jars into the red5/plugins folder:
derby-10.5.3.0.jar
commons-dbcp-1.2.2.jar
spring-jdbc-2.5.6.jar
spring-orm-2.5.6.jar
spring-security-core-2.5.6.jar
spring-tx-2.5.6.jar

3. but when I open the Admin.jsp I got the following errors (the Admin.jsp was 
working with red5 0.9.1)

avax.servlet.ServletException: java.lang.NoClassDefFoundError: 
org/apache/el/ExpressionFactoryImpl
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:268)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

root cause

java.lang.NoClassDefFoundError: org/apache/el/ExpressionFactoryImpl
    org.apache.jasper.JspCompilationContext.getServletClassName(JspCompilationContext.java:371)
    org.apache.jasper.JspCompilationContext.getClassFileName(JspCompilationContext.java:511)
    org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:445)
    org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:392)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:582)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

root cause

java.lang.ClassNotFoundException: org.apache.el.ExpressionFactoryImpl
    java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    java.security.AccessController.doPrivileged(Native Method)
    java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    java.lang.ClassLoader.loadClass(ClassLoader.java:319)
    java.lang.ClassLoader.loadClass(ClassLoader.java:264)
    java.lang.ClassLoader.loadClassInternal(ClassLoader.java:332)
    org.apache.jasper.JspCompilationContext.getServletClassName(JspCompilationContext.java:371)
    org.apache.jasper.JspCompilationContext.getClassFileName(JspCompilationContext.java:511)
    org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:445)
    org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:392)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:582)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

3.

What is the expected output? What do you see instead?
no errors please

What version of the product are you using? On what operating system?
red5 1.0 r4195

```

Original issue reported on code.google.com by `marcus.f...@googlemail.com` on 15 Feb 2011 at 10:59
